// Same community partners as the DevFest Chandigarh 2026 site. `dark` puts a
// white logo on a dark tile so it stays visible.
export const COMMUNITY_PARTNERS: { name: string; img: string; dark?: boolean }[] = [
  { name: "ACM Chapter, CCE", img: "/partners/acm-chapter-cce.jpg" },
  { name: "Alexa Developers Community, Chandigarh University", img: "/partners/alexa-developers-community-cu.png" },
  { name: "BUG2BUILD", img: "/partners/bug2build.jpg" },
  { name: "Builders Hub", img: "/partners/builders-hub.jpg" },
  { name: "C Square", img: "/partners/c-square.png" },
  { name: "Code Zen", img: "/partners/code-zen.jpg" },
  { name: "Devantra", img: "/partners/devantra.jpg" },
  { name: "Devengers", img: "/partners/devengers.jpg" },
  { name: "DevPath", img: "/partners/devpath.jpg" },
  { name: "E-Cell CEC, CGC Landran", img: "/partners/ecell-cec-cgc-landran.jpg" },
  { name: "E-Cell CGC-COE", img: "/partners/ecell-cgc-coe.jpg" },
  { name: "Fusion", img: "/partners/fusion.png", dark: true },
  { name: "GDG On Campus SVIET", img: "/partners/gdg-on-campus-sviet.jpg" },
  { name: "GeeksforGeeks Campus Body, Chandigarh University", img: "/partners/gfg-campus-body-cu.webp" },
  { name: "Hacknfinity", img: "/partners/hacknfinity.jpg" },
  { name: "OSEN Chandigarh", img: "/partners/osen-chandigarh.jpg" },
  { name: "Project Hub Community", img: "/partners/project-hub.jpg" },
  { name: "Recess Tribe Community", img: "/partners/recess-tribe.jpg" },
  { name: "SheBuilds", img: "/partners/shebuilds.jpg" },
  { name: "SkillBugz", img: "/partners/skillbugz.jpg" },
  { name: "Spark Tech AI Hub", img: "/partners/spark-tech-ai-hub.jpg" },
  { name: "The Ascent Circle", img: "/partners/the-ascent-circle.webp" },
  { name: "The Uniques Community", img: "/partners/the-uniques.png" },
  { name: "The Visionary Minds", img: "/partners/the-visionary-minds.jpg" },
  { name: "Venture Nexus", img: "/partners/venture-nexus.jpg" },
];
